CREATE TABLE netology.customers
(
    Id INT PRIMARY KEY generated by default  as identity,
    FirstName VARCHAR(255),
    SurName VARCHAR(255),
    Age INT,
    PhoneNumber INT,
);

insert into CUSTOMERS (FirstName, SurName, Age, PhoneNumber)
values ('Anna', 'Petrova', 31, '+71234567890');