CREATE TABLE netology.orders
(
    id int generated by default as identity primary key,
    date timestamp not null,
    customer_id int,
    product_name varchar not null,
    amount int not null,
    foreign key (customer_id) references netology.CUSTOMERS(id)
);

insert into netology.ORDERS (date, customer_id, product_name, amount)
VALUES (current_date, 2, 'phone', 2);